# Generated by Django 4.1.2 on 2022-10-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.BigIntegerField()),
                ('nombre_empleado', models.CharField(max_length=256)),
                ('fecha_de_contratacion', models.DateField()),
                ('RFC', models.CharField(max_length=256)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_piezas', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=256)),
                ('cantidad_piezas', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orden_piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.BigIntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homne.piezas')),
                ('nombre_empleado', models.ManyToManyField(to='homne.employees')),
            ],
        ),
    ]
